[package]
rust-version.workspace = true
name = "sdkwork-routes-gameengine-catalog-app-api"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "SDKWork games catalog app-api router."


[lints]
workspace = true
[lib]
name = "sdkwork_routes_gameengine_catalog_app_api"
path = "src/lib.rs"

[dependencies]
sdkwork-web-core.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork_game_catalog_service.workspace = true
sdkwork_routes_games_support.workspace = true
sdkwork-web-axum.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio.workspace = true
